version: "3"
services:
  nextjs:
    build: client
    # ports:
    #   - 3000:3000
    restart: always

  nginx:
    build: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    restart: always
